Article.create!([
  {page_id: 1, name: "HTML", position: 1, visible: true, content: "HyperText Markup Language, commonly referred to as HTML, is the standard markup language used to create web pages. Along with CSS, and JavaScript, HTML is a cornerstone technology, used by most websites to create visually engaging webpages, user interfaces for web applications, and user interfaces for many mobile applications.[1] Web browsers can read HTML files and render them into visible or audible web pages. HTML describes the structure of a website semantically along with cues for presentation, making it a markup language, rather than a programming language.\r\n\r\nHTML elements form the building blocks of all websites. HTML allows images and objects to be embedded and can be used to create interactive forms. It provides a means to create structured documents by denoting structural semantics for text such as headings, paragraphs, lists, links, quotes and other items.", photo_file_name: "html.jpg", photo_content_type: "image/jpeg", photo_file_size: 24324, photo_updated_at: "2016-02-02 12:29:33"},
  {page_id: 1, name: "JS", position: 1, visible: true, content: "JavaScript (/ˈdʒɑːvəˌskrɪpt/[5]) is a high-level, dynamic, untyped, and interpreted programming language.[6] It has been standardized in the ECMAScript language specification.[7] Alongside HTML and CSS, it is one of the three essential technologies of World Wide Web content production; the majority of websites employ it and it is supported by all modern Web browsers without plug-ins.[6] JavaScript is prototype-based with first-class functions, making it a multi-paradigm language, supporting object-oriented,[8] imperative, and functional programming styles.[6] It has an API for working with text, arrays, dates and regular expressions, but does not include any I/O, such as networking, storage, or graphics facilities, relying for these upon the host environment in which it is embedded.[7]\r\n\r\nDespite some naming, syntactic, and standard library similarities, JavaScript and Java are otherwise unrelated and have very different semantics. The syntax of JavaScript is actually derived from C, while the semantics and design are influenced by the Self and Scheme programming languages.[9]", photo_file_name: "js.jpg", photo_content_type: "image/jpeg", photo_file_size: 22547, photo_updated_at: "2016-02-02 12:29:52"},
  {page_id: 1, name: "CSS", position: 1, visible: true, content: "Cascading Style Sheets (CSS) is a style sheet language used for describing the presentation of a document written in a markup language.[1] Although most often used to set the visual style of web pages and user interfaces written in HTML and XHTML, the language can be applied to any XML document, including plain XML, SVG and XUL, and is applicable to rendering in speech, or on other media. Along with HTML and JavaScript, CSS is a cornerstone technology used by most websites to create visually engaging webpages, user interfaces for web applications, and user interfaces for many mobile applications.[2]\r\n\r\nCSS is designed primarily to enable the separation of document content from document presentation, including aspects such as the layout, colors, and fonts.[3] This separation can improve content accessibility, provide more flexibility and control in the specification of presentation characteristics, enable multiple HTML pages to share formatting by specifying the relevant CSS in a separate .css file, and reduce complexity and repetition in the structural content, such as semantically insignificant tables that were widely used to format pages before consistent CSS rendering was available in all major browsers. CSS makes it possible to separate presentation instructions from the HTML content in a separate file or style section of the HTML file. For each matching HTML element, it provides a list of formatting instructions. For example, a CSS rule might specify that \"all heading 1 elements should be bold\", leaving pure semantic HTML markup that asserts \"this text is a level 1 heading\" without formatting code such as a <bold> tag indicating how such text should be displayed.", photo_file_name: "css.jpg", photo_content_type: "image/jpeg", photo_file_size: 24083, photo_updated_at: "2016-02-02 12:30:57"}
])
Category.create!([
  {name: "Pierwsza kategoria", position: 1, visible: true},
  {name: "Druga kategoria", position: 2, visible: true}
])
Gallery.create!([
  {name: "nowa galeria", position: 1, description: "jakis opis galerii jakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galerii", visible: true, photo_file_name: "jmobile.jpg", photo_content_type: "image/jpeg", photo_file_size: 57332, photo_updated_at: "2016-02-04 12:35:46"},
  {name: "nowa galeria 2", position: 1, description: "jakis opis galerii jakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galeriijakis opis galerii", visible: true, photo_file_name: "rwd.jpg", photo_content_type: "image/jpeg", photo_file_size: 51161, photo_updated_at: "2016-02-04 12:36:02"}
])
Page.create!([
  {category_id: 1, name: "Pierwsza strona Pierwsza kategoria", position: 1, visible: true},
  {category_id: 1, name: "Druga strona Pierwsza kategoria", position: 2, visible: true},
  {category_id: 2, name: "Pierwsza strona Druga kategoria", position: 1, visible: true},
  {category_id: 2, name: "Druga strona Druga kategoria", position: 2, visible: true}
])
Photo.create!([
  {gallery_id: 1, name: "zdjecie 1", position: 1, visible: true, description: "CSS", photo_file_name: "css.jpg", photo_content_type: "image/jpeg", photo_file_size: 24083, photo_updated_at: "2016-02-04 09:06:09"},
  {gallery_id: 1, name: "zdjecie 2", position: 1, visible: true, description: "HTML", photo_file_name: "html.jpg", photo_content_type: "image/jpeg", photo_file_size: 24324, photo_updated_at: "2016-02-04 09:06:38"},
  {gallery_id: 1, name: "zdjecie 3", position: 1, visible: true, description: "JS", photo_file_name: "js.jpg", photo_content_type: "image/jpeg", photo_file_size: 22547, photo_updated_at: "2016-02-04 09:06:58"},
  {gallery_id: 1, name: "zdjecie 4", position: 1, visible: true, description: "JMobile", photo_file_name: "jmobile.jpg", photo_content_type: "image/jpeg", photo_file_size: 57332, photo_updated_at: "2016-02-04 09:07:17"},
  {gallery_id: 1, name: "zdjecie 5", position: 1, visible: true, description: "mobile", photo_file_name: "rwd.jpg", photo_content_type: "image/jpeg", photo_file_size: 51161, photo_updated_at: "2016-02-04 09:07:34"}
])
User.create!([
  {first_name: "Krystian", last_name: "Guzara", login: "guzik", email: "kg@.zpas.pl", phone_number: "", password_digest: "$2a$10$kzMiYynOaJl8JCZ6GAvGbuB07S.en9UJPenclynLISvZ1gyP5dDOe"},
  {first_name: "admin", last_name: "admin", login: "admin", email: "admin@admin.pl", phone_number: "", password_digest: "$2a$10$1NHLNQ.n4W2j2wdEK4TVz.k3ouzSliSJlMTW1fFVqUDu7P4MZiYMW"}
])
